// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for Android and iOS.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'Malomati supports Android and iOS only.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaqgvg0ifu3xvyu6qq5PCIuGtVVt_Yj90',
    appId: '1:393239977540:android:687c4f47887c8836a82611',
    messagingSenderId: '393239977540',
    projectId: 'malomati-bf7ab',
    storageBucket: 'malomati-bf7ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMRFioYW3ahpc35Li8KcES7-STddLNiv0',
    appId: '1:393239977540:ios:8d559e1fad714c50a82611',
    messagingSenderId: '393239977540',
    projectId: 'malomati-bf7ab',
    storageBucket: 'malomati-bf7ab.appspot.com',
    androidClientId:
        '393239977540-e3b8rk9c5phg95u1iljqag71an2555f0.apps.googleusercontent.com',
    iosBundleId: 'com.gov.uaq.hrm',
  );
}
